// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxyDKvgPpR27PM8oPfNZZbEA3RcEGKTD4',
    appId: '1:555934121480:web:6278e9b93063fec4a2dbbd',
    messagingSenderId: '555934121480',
    projectId: 'taste-guide-app',
    authDomain: 'taste-guide-app.firebaseapp.com',
    storageBucket: 'taste-guide-app.firebasestorage.app',
    measurementId: 'G-FZFNGHMP7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeccn8XWmXsu1es-rzyyFJepVWsgi3Md0',
    appId: '1:555934121480:android:4f90a7d45b8255a2a2dbbd',
    messagingSenderId: '555934121480',
    projectId: 'taste-guide-app',
    storageBucket: 'taste-guide-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0zKPFIiw5Etnj2qSDTh2_LqLd2iIsL0E',
    appId: '1:555934121480:ios:26e6c42e19b4a8eaa2dbbd',
    messagingSenderId: '555934121480',
    projectId: 'taste-guide-app',
    storageBucket: 'taste-guide-app.firebasestorage.app',
    iosBundleId: 'com.example.tasteGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0zKPFIiw5Etnj2qSDTh2_LqLd2iIsL0E',
    appId: '1:555934121480:ios:26e6c42e19b4a8eaa2dbbd',
    messagingSenderId: '555934121480',
    projectId: 'taste-guide-app',
    storageBucket: 'taste-guide-app.firebasestorage.app',
    iosBundleId: 'com.example.tasteGuideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxyDKvgPpR27PM8oPfNZZbEA3RcEGKTD4',
    appId: '1:555934121480:web:09c74a1f784981a7a2dbbd',
    messagingSenderId: '555934121480',
    projectId: 'taste-guide-app',
    authDomain: 'taste-guide-app.firebaseapp.com',
    storageBucket: 'taste-guide-app.firebasestorage.app',
    measurementId: 'G-0M3XVN4PSS',
  );

}